server:
  port: 8001
spring:
  application:
    name: qbike-intention    # 项目名称尽量用小写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
#    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
#    data: classpath:data.sql            # 指定h2数据库的insert脚本
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true